name: renovate-config-validator

on:
  push:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v0.1.2
